### ISSUE TITLE
Migrate to Godot 4

### ISSUE THREAD

**Issue by toedter** [Cafezinhu/godot-vr-simulator#1]
This is awesome and exactly what I was looking for when developing my XR game!

Could you please migrate it to Godot 4?

**Comment by Cafezinhu** [comment]
Done!
https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v1.0.1

**Comment by Cafezinhu** [comment]
Also I updated the input mapping a bit, you can read the updated mapping on the README
https://github.com/Cafezinhu/godot-vr-simulator/blob/main/README.md

**Comment by toedter** [comment]
Thank you very much!

In your project, wasd works perfectly. But in my [XR demo](https://github.com/toedter/godot-xr-game-demo), that is based on [XR Tools](https://github.com/GodotVR/godot-xr-tools), I can't simulate the left controller's joystick with wasd.

The easiest way to reproduce would be to add the vr-simulator to the [XR Tools Basic Movement scene](https://github.com/GodotVR/godot-xr-tools/tree/master/scenes/basic_movement_demo). There, wasd is also not working.

I also could not figure out how to simulate jump (right A button) in the XR Tools demo.

May be it is just a configuration. Any hints?

**Comment by Cafezinhu** [comment]
There was a problem that the controller wasn't activating if its pose wasn't set to "default". It should work with all poses now.
https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v1.0.2

**Comment by toedter** [comment]
Thx a lot, again! wasd is working now!

But I could not get the controller buttons working. In the XR Tools demo, jump is bound to the right controller's AX button. 
Pressing 2 (or any other number) on the num pad has no effect.

Any hints?

**Comment by Cafezinhu** [comment]
Hold Q (or E) and press 2 (the one that is above the letter keys).
Pressing 2 while holding Q will press ``X`` on the left controller, and pressing 2 while holding E will press ``A`` on the right controller.
Holding Q or E makes the tool select the left or the right controller, respectively, allowing you to move, rotate and press its buttons.

**Comment by toedter** [comment]
Ah, I see. It's working perfectly. Thank you so much for your quick response and porting it to Godot 4. I will mention your simulator in my readme :).
