### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by MatthewBernardon** [Cafezinhu/godot-vr-simulator#4]
Followed Bastiaan Olij's tutorial and got everything working with the headset, but after I added the simulator node and added the xr origin to the parameter I am just getting black screen with the following errors:
1. E 0:00:00:0056   create_instance: Failed to create XR instance.
  <C++ Error>    Condition "((result) < 0)" is true. Returning: false
  <C++ Source>   modules/openxr/openxr_api.cpp:371 @ create_instance()
2. E 0:00:02:0315   user_settings.gd:34 @ _ready(): Interface not found.
  <C++ Error>    Condition "idx == -1" is true. Returning: nullptr
  <C++ Source>   servers/xr_server.cpp:224 @ find_interface()
  <Stack Trace>  user_settings.gd:34 @ _ready()
3. 	E 0:00:02:0319   player_body.gd:424 @ _estimate_body_forward_dir(): The axis Vector3 must be normalized.
  <C++ Error>    Condition "!p_axis.is_normalized()" is true.
  <C++ Source>   core/math/basis.cpp:829 @ set_axis_angle()
  <Stack Trace>  player_body.gd:424 @ _estimate_body_forward_dir()
                 player_body.gd:457 @ _update_body_under_camera()
                 player_body.gd:246 @ _physics_process()

The first two errors I get even without the simulator node active, so I assume those are caused by the lack of VR headset connected. However, the third is only triggered with the simulator active. Commenting out the line that triggers the error removes the error but does still produces a black screen. I'm sure I messed something up, if you know what the error is I would greatly appreciate help.

**Comment by Cafezinhu** [comment]
The black screen usually happens because Viewport.use_xr is being set to true. 
I release an update that allows you to disable use_xr by pressing F11.

Download the update
https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v1.0.3
and press F11 if you see a black screen

Hope this can help.

**Comment by MatthewBernardon** [comment]
Yup, that was the issue.

Thank you so much!
