### ISSUE TITLE
OpenXR: No viewport was marked with use_xr, there is no rendered output!

### ISSUE THREAD

**Issue by Muhammad-Hazimi-Yusri** [Cafezinhu/godot-vr-simulator#8]
I got that error message when running on the editor (works fine after exporting), and getting black VR screen output, most likely due to this addon, even after disabling it, the issue persists, only after I removed it from autoload, the issue resolves. I assume this is unintended behaviour, and would be pretty annoying to debug without warning/disclaimer.
![image](https://github.com/Cafezinhu/godot-vr-simulator/assets/126186721/8295b35c-699d-42ee-8ee5-ce0d331e6485)

**Comment by Cafezinhu** [comment]
To use a VR headset while also using the simulator, go to addons/xr-simulator/XRSimulator.tscn and disable "Disable XR in Editor"
![image](https://github.com/Cafezinhu/godot-vr-simulator/assets/38568712/62350fe6-c859-4072-95cb-0b31594aa631)
I added that option in case you forget your headset connected while trying to use the simulator. Now I think of making that option disabled by default.
